# Generated by Django 5.1.2 on 2024-11-06 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('ambientes', models.CharField(max_length=2)),
                ('precio', models.CharField(max_length=15)),
                ('moneda', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.localidad')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipopropiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionTipoOper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionTipoProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipopropiedad')),
            ],
        ),
    ]
