# Generated by Django 5.1.3 on 2024-11-12 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedad', '0002_initial'),
        ('publicacion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentepublicacion',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.agente'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.localidad'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipopropiedad'),
        ),
        migrations.AddField(
            model_name='agentepublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion'),
        ),
        migrations.AddField(
            model_name='publicaciontipooper',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion'),
        ),
        migrations.AddField(
            model_name='publicaciontipooper',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion'),
        ),
        migrations.AddField(
            model_name='publicaciontipoprop',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion'),
        ),
        migrations.AddField(
            model_name='publicaciontipoprop',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipopropiedad'),
        ),
    ]
