# Generated by Django 5.1.3 on 2025-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='localidad',
            field=models.CharField(max_length=25),
        ),
    ]
