# Generated by Django 5.1.3 on 2025-05-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_alter_publicacion_localidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='localidad',
            new_name='barrio',
        ),
    ]
