# Generated by Django 5.1.1 on 2024-10-01 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busqueda', '0001_initial'),
        ('tipo_propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaTipoProp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busqueda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='busqueda.busqueda')),
                ('tipo_propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tipo_propiedad.tipo_propiedad')),
            ],
        ),
    ]
