# Generated by Django 5.1.1 on 2024-10-01 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agente', '0001_initial'),
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente_busqueda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agente.agente')),
                ('busqueda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='busqueda.busqueda')),
            ],
        ),
    ]
