# Generated by Django 5.1.1 on 2024-10-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agente', '0001_initial'),
        ('localidad', '0001_initial'),
        ('tipo_propiedad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambientes', models.CharField(max_length=2)),
                ('dormitorios', models.CharField(max_length=2)),
                ('banios', models.CharField(max_length=2)),
                ('amenities', models.CharField(max_length=255)),
                ('cochera', models.CharField(max_length=2)),
                ('metros_cuadrados', models.CharField(max_length=4)),
                ('precio', models.CharField(max_length=15)),
                ('moneda', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.agente')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad.localidad')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_propiedad.tipopropiedad')),
            ],
        ),
    ]
