# Generated by Django 5.1.3 on 2024-11-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='sin titulo', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ambientes', models.PositiveIntegerField()),
                ('metros_cuadrados', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=55)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.localidad')),
                ('tipo_operacion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipopropiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_url', models.URLField(max_length=255)),
                ('descripcion_foto', models.CharField(max_length=255)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
