# Generated by Django 5.1.3 on 2025-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_initial'),
        ('publicacion', '0003_alter_publicacion_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='localidad',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
