# Generated by Django 5.1.3 on 2024-11-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_propiedad_agente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='agente',
        ),
    ]
