# Generated by Django 5.1.3 on 2024-11-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_alter_propiedad_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(default='sin titulo', max_length=50),
        ),
    ]
