# Generated by Django 5.1.3 on 2024-11-17 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_remove_propiedad_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion'),
        ),
    ]
