# Generated by Django 5.1.3 on 2025-05-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_alter_propiedad_localidad_delete_localidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='localidad',
            new_name='barrio',
        ),
    ]
