# Generated by Django 5.1.3 on 2024-11-17 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_alter_propiedad_tipo_operacion'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='agente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.agente'),
            preserve_default=False,
        ),
    ]
