# Generated by Django 5.1.3 on 2024-11-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_propiedad_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo_operacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='propiedad.tipooperacion'),
        ),
    ]
