# Generated by Django 5.1.3 on 2025-06-05 21:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_rename_localidad_propiedad_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
