# Generated by Django 5.1.3 on 2024-11-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_propiedad_tipo_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='agente',
        ),
    ]
