# Generated by Django 5.1.3 on 2024-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0006_remove_propiedad_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='foto',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
