# Generated by Django 5.1.3 on 2024-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0008_alter_propiedad_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
