# Generated by Django 5.1.3 on 2024-11-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0010_alter_propiedad_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
