# Generated by Django 5.1.1 on 2024-10-01 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad_foto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_url', models.CharField(max_length=255)),
                ('descripcion_foto', models.CharField(max_length=255)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
