# Generated by Django 5.1.2 on 2024-11-06 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agente', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentebusqueda',
            name='busqueda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion'),
        ),
    ]
